### ISSUE TITLE
Добавить определение или установку версии платформы

### ISSUE THREAD

**Issue by ivanmolodec** [firstBitSportivnaya/files-converter#19]
https://github.com/firstBitSportivnaya/files-converter/blob/caaa8931f2111f32de378e8d61e3c02d6fa16bf6/pkg/converter/srcToCfe.go#L32

Версию платформы нужно определять по исходникам (сделать соответствие версии конфигурации и версии в исходниках, по исходникам определять номер платформы и пытаться искать её на машине - если нет, завершать конвертацию с ошибкой). 

Дополнительный вариант - устанавливать конкретную версию в параметрах командной строки или конфигурационном файле

**Comment by denisushakov** [comment]
Определение версии из исходных файлов будет работать только для режима src, в случае с cf, невозможно заранее определить версию формата выгрузки, т.к. при загрузке cf и последующей выгрузки, версия формата выгрузки будет установлена по умолчанию в зависимости от запущенной версии платформы, в таком случае нужно указать в конфигурационном файле или версия платформы будет по умолчанию. Описать в документации.
