### ISSUE TITLE
Доработать автоматическую проверку привилегированных модулей по свойствам конфигурации

### ISSUE THREAD

**Issue by ivanmolodec** [firstBitSportivnaya/files-converter#5]
Доработать автоматическую проверку привилегированных модулей по свойствам конфигурации
https://github.com/firstBitSportivnaya/files-converter/blob/a4616d43ddf725088066428c57e9fe72c93a9ae9/pkg/file_modifier/change.go#L16

**Comment by denisushakov** [comment]
Поиск будет в каталоге CommonModules
