### ISSUE TITLE
Добавить возможность указать параметры запуска приложения

### ISSUE THREAD

**Issue by ivanmolodec** [firstBitSportivnaya/files-converter#7]
Как сейчас:
```
./src-files-converter.exe
Введите путь к исходным файлам: C:\path\to\source
Введите путь для сохранения файла .cfe: C:\path\to\output
```
Сделать одной командой:
`./src-files-converter.exe "C:\path\to\source" "C:\path\to\output"`

**Comment by denisushakov** [comment]
Выбор варианта работы будет определяться параметрами запуска, возможно оставлю отдельный запуск
./src-files-converter srcConvert -i "C:\path\to\source" -o "C:\path\to\output"
./src-files-converter cfConvert -i "C:\path\to\source" -o "C:\path\to\output"
